import { useState, useEffect } from 'react';
import { ArrowLeft, Plus, X, Clock, FileText, Search, Download, Trash2, Tag, AlertTriangle, CheckCircle2, ExternalLink } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';
import { BlockchainLookup } from './BlockchainLookup';
import { ForensicTimeline } from './ForensicTimeline';

interface Evidence {
  id: string;
  type: string;
  label: string;
  value: string | null;
  metadata: Record<string, unknown>;
  tags: string[];
  created_at: string;
}

interface CaseData {
  id: string;
  title: string;
  description: string | null;
  status: string;
  scam_type: string | null;
  total_loss: number | null;
  currency: string;
  created_at: string;
}

export function CaseDetail({ caseId, onBack }: { caseId: string; onBack: () => void }) {
  const { user } = useAuth();
  const [caseData, setCaseData] = useState<CaseData | null>(null);
  const [evidence, setEvidence] = useState<Evidence[]>([]);
  const [tab, setTab] = useState<'evidence' | 'timeline' | 'blockchain' | 'report'>('evidence');
  const [showAdd, setShowAdd] = useState(false);
  const [loading, setLoading] = useState(true);

  // New evidence form
  const [evType, setEvType] = useState('transaction');
  const [evLabel, setEvLabel] = useState('');
  const [evValue, setEvValue] = useState('');
  const [evTags, setEvTags] = useState('');
  const [adding, setAdding] = useState(false);

  useEffect(() => {
    fetchCase();
    fetchEvidence();
  }, [caseId]);

  const fetchCase = async () => {
    const { data } = await supabase.from('cases').select('*').eq('id', caseId).single();
    setCaseData(data as CaseData);
    setLoading(false);
  };

  const fetchEvidence = async () => {
    const { data } = await supabase.from('evidence').select('*').eq('case_id', caseId).order('created_at', { ascending: false });
    setEvidence((data as Evidence[]) ?? []);
  };

  const addEvidence = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!evLabel.trim() || !user) return;
    setAdding(true);
    await supabase.from('evidence').insert({
      case_id: caseId,
      user_id: user.id,
      type: evType,
      label: evLabel.trim(),
      value: evValue.trim() || null,
      tags: evTags ? evTags.split(',').map(t => t.trim()).filter(Boolean) : [],
    });
    setAdding(false);
    setEvLabel('');
    setEvValue('');
    setEvTags('');
    setShowAdd(false);
    fetchEvidence();
  };

  const deleteEvidence = async (id: string) => {
    await supabase.from('evidence').delete().eq('id', id);
    fetchEvidence();
  };

  const exportCSV = () => {
    if (!caseData) return;
    const headers = ['Type', 'Label', 'Value', 'Tags', 'Date'];
    const rows = evidence.map(e => [e.type, e.label, e.value ?? '', (e.tags ?? []).join('; '), new Date(e.created_at).toISOString()]);
    const csv = [headers, ...rows].map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scamtrace-case-${caseId.slice(0, 8)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportPDF = () => {
    if (!caseData) return;
    let content = `SCAMTRACE EVIDENCE REPORT\n${'='.repeat(50)}\n\n`;
    content += `Case: ${caseData.title}\n`;
    content += `Status: ${caseData.status}\n`;
    content += `Scam Type: ${caseData.scam_type ?? 'N/A'}\n`;
    content += `Total Loss: ${caseData.total_loss != null ? `$${caseData.total_loss.toLocaleString()} ${caseData.currency}` : 'N/A'}\n`;
    content += `Created: ${new Date(caseData.created_at).toLocaleDateString()}\n`;
    content += `\n${'-'.repeat(50)}\nEVIDENCE ITEMS (${evidence.length})\n${'-'.repeat(50)}\n\n`;
    evidence.forEach((ev, i) => {
      content += `${i + 1}. [${ev.type.toUpperCase()}] ${ev.label}\n`;
      if (ev.value) content += `   Value: ${ev.value}\n`;
      if (ev.tags?.length) content += `   Tags: ${ev.tags.join(', ')}\n`;
      content += `   Date: ${new Date(ev.created_at).toISOString()}\n\n`;
    });
    content += `\n${'-'.repeat(50)}\nDISCLAIMER\n${'-'.repeat(50)}\n`;
    content += `This report was generated by ScamTrace for informational purposes only.\nIt does not constitute legal advice and does not guarantee fund recovery.\nGenerated: ${new Date().toISOString()}\n`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scamtrace-report-${caseId.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading || !caseData) {
    return <div className="py-24 text-center text-slate-500">Loading case...</div>;
  }

  const typeColors: Record<string, string> = {
    transaction: 'bg-cyber-green/10 text-cyber-green border-cyber-green/20',
    wallet: 'bg-cyber-blue/10 text-cyber-blue border-cyber-blue/20',
    screenshot: 'bg-cyber-purple/10 text-cyber-purple border-cyber-purple/20',
    chat_log: 'bg-cyan-400/10 text-cyan-400 border-cyan-400/20',
    domain: 'bg-blue-400/10 text-blue-400 border-blue-400/20',
    phone: 'bg-green-400/10 text-green-400 border-green-400/20',
    note: 'bg-slate-400/10 text-slate-400 border-slate-400/20',
    other: 'bg-white/5 text-slate-400 border-white/10',
  };

  return (
    <section className="py-24">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <button onClick={onBack} className="mb-6 text-sm text-slate-400 hover:text-white transition flex items-center gap-1">
          <ArrowLeft className="h-4 w-4" /> Back to Cases
        </button>

        <div className="flex flex-col sm:flex-row items-start justify-between gap-4 mb-8">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h1 className="text-2xl font-bold text-white">{caseData.title}</h1>
              <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium capitalize ${
                caseData.status === 'open' ? 'bg-cyber-orange/10 text-cyber-orange border border-cyber-orange/20' :
                caseData.status === 'closed' ? 'bg-cyber-green/10 text-cyber-green border border-cyber-green/20' :
                'bg-slate-400/10 text-slate-400 border border-white/10'
              }`}>
                {caseData.status === 'open' ? <AlertTriangle className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}
                {caseData.status}
              </span>
            </div>
            {caseData.description && <p className="text-sm text-slate-400">{caseData.description}</p>}
            <div className="flex flex-wrap gap-3 mt-2 text-xs text-slate-500">
              {caseData.scam_type && <span className="bg-white/5 border border-white/10 rounded-full px-2.5 py-0.5">{caseData.scam_type.replace('_', ' ')}</span>}
              {caseData.total_loss != null && <span className="text-cyber-red font-medium">${caseData.total_loss.toLocaleString()}</span>}
              <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> {new Date(caseData.created_at).toLocaleDateString()}</span>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 mb-6 border-b border-white/5 overflow-x-auto">
          {[
            { key: 'evidence', label: 'Evidence', icon: FileText },
            { key: 'timeline', label: 'Timeline', icon: Clock },
            { key: 'blockchain', label: 'Blockchain Lookup', icon: Search },
            { key: 'report', label: 'Export Report', icon: Download },
          ].map(t => (
            <button key={t.key} onClick={() => setTab(t.key as typeof tab)}
              className={`flex items-center gap-2 px-4 py-3 text-sm font-medium transition border-b-2 whitespace-nowrap ${
                tab === t.key ? 'border-cyber-green text-cyber-green' : 'border-transparent text-slate-400 hover:text-white'
              }`}>
              <t.icon className="h-4 w-4" /> {t.label}
              {t.key === 'evidence' && <span className="rounded-full bg-white/10 px-1.5 py-0.5 text-[10px]">{evidence.length}</span>}
            </button>
          ))}
        </div>

        {/* Evidence Tab */}
        {tab === 'evidence' && (
          <div>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-white">Evidence Items</h3>
              <button onClick={() => setShowAdd(true)} className="rounded-lg bg-cyber-green/10 text-cyber-green px-4 py-2 text-xs font-medium hover:bg-cyber-green/20 transition flex items-center gap-1">
                <Plus className="h-3.5 w-3.5" /> Add Evidence
              </button>
            </div>

            {evidence.length === 0 ? (
              <div className="text-center py-12 glass-card rounded-xl">
                <FileText className="h-10 w-10 text-slate-600 mx-auto mb-3" />
                <p className="text-slate-400 font-medium">No evidence yet</p>
                <p className="text-xs text-slate-500 mt-1">Add wallet addresses, transaction hashes, chat logs, and more.</p>
              </div>
            ) : (
              <div className="space-y-2">
                {evidence.map(ev => (
                  <div key={ev.id} className="glass-card rounded-xl p-4 flex items-start justify-between gap-4">
                    <div className="flex items-start gap-3 min-w-0">
                      <span className={`inline-block rounded-full border px-2 py-0.5 text-[10px] font-medium capitalize whitespace-nowrap ${typeColors[ev.type] ?? typeColors.other}`}>
                        {ev.type.replace('_', ' ')}
                      </span>
                      <div className="min-w-0">
                        <h4 className="font-medium text-white text-sm">{ev.label}</h4>
                        {ev.value && <p className="text-xs text-slate-400 font-mono mt-0.5 truncate max-w-md">{ev.value}</p>}
                        {ev.tags?.length > 0 && (
                          <div className="flex gap-1 mt-1.5">
                            {ev.tags.map(t => (
                              <span key={t} className="flex items-center gap-0.5 rounded-full bg-white/5 px-2 py-0.5 text-[10px] text-slate-400">
                                <Tag className="h-2.5 w-2.5" />{t}
                              </span>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <span className="text-[10px] text-slate-500">{new Date(ev.created_at).toLocaleDateString()}</span>
                      <button onClick={() => deleteEvidence(ev.id)} className="rounded p-1 text-slate-500 hover:text-red-400 transition">
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Add evidence modal */}
            {showAdd && (
              <div className="fixed inset-0 z-[100] flex items-center justify-center p-4" onClick={() => setShowAdd(false)}>
                <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" />
                <div className="relative w-full max-w-md rounded-2xl border border-white/10 bg-dark-800 shadow-2xl animate-fade-in-up" onClick={e => e.stopPropagation()}>
                  <div className="flex items-center justify-between px-6 pt-6 pb-4">
                    <h3 className="text-lg font-bold text-white">Add Evidence</h3>
                    <button onClick={() => setShowAdd(false)} className="text-slate-400 hover:text-white transition"><X className="h-5 w-5" /></button>
                  </div>
                  <form onSubmit={addEvidence} className="px-6 pb-6 space-y-4">
                    <div>
                      <label className="text-xs text-slate-400 block mb-1.5">Type</label>
                      <select value={evType} onChange={e => setEvType(e.target.value)}
                        className="w-full rounded-xl border border-white/10 bg-dark-900 py-3 px-4 text-sm text-white outline-none focus:border-cyber-green/50 transition">
                        <option value="transaction">Transaction Hash</option>
                        <option value="wallet">Wallet Address</option>
                        <option value="screenshot">Screenshot</option>
                        <option value="chat_log">Chat Log</option>
                        <option value="domain">Domain</option>
                        <option value="phone">Phone Number</option>
                        <option value="note">Note</option>
                        <option value="other">Other</option>
                      </select>
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1.5">Label *</label>
                      <input type="text" value={evLabel} onChange={e => setEvLabel(e.target.value)} placeholder="e.g., Initial transfer to scammer"
                        className="w-full rounded-xl border border-white/10 bg-dark-900 py-3 px-4 text-sm text-white placeholder-slate-500 outline-none focus:border-cyber-green/50 transition" />
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1.5">Value (hash, address, URL, etc.)</label>
                      <input type="text" value={evValue} onChange={e => setEvValue(e.target.value)} placeholder="0x..."
                        className="w-full rounded-xl border border-white/10 bg-dark-900 py-3 px-4 text-sm text-white font-mono placeholder-slate-500 outline-none focus:border-cyber-green/50 transition" />
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1.5">Tags (comma-separated)</label>
                      <input type="text" value={evTags} onChange={e => setEvTags(e.target.value)} placeholder="suspicious, mixer, bridge"
                        className="w-full rounded-xl border border-white/10 bg-dark-900 py-3 px-4 text-sm text-white placeholder-slate-500 outline-none focus:border-cyber-green/50 transition" />
                    </div>
                    <button type="submit" disabled={adding || !evLabel.trim()}
                      className="w-full rounded-xl bg-gradient-to-r from-cyber-green to-cyber-blue py-3 text-sm font-bold text-dark-900 transition hover:shadow-lg disabled:opacity-50">
                      {adding ? 'Adding...' : 'Add Evidence'}
                    </button>
                  </form>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Timeline Tab */}
        {tab === 'timeline' && <ForensicTimeline caseId={caseId} evidence={evidence} />}

        {/* Blockchain Tab */}
        {tab === 'blockchain' && <BlockchainLookup caseId={caseId} />}

        {/* Report Tab */}
        {tab === 'report' && (
          <div className="glass-card-premium rounded-2xl p-8 text-center">
            <Download className="h-12 w-12 text-cyber-green mx-auto mb-4" />
            <h3 className="text-xl font-bold text-white mb-2">Export Evidence Report</h3>
            <p className="text-sm text-slate-400 mb-6 max-w-md mx-auto">
              Generate a comprehensive report of all evidence, timeline events, and case details. Suitable for exchange freeze requests and law enforcement filings.
            </p>
            <div className="flex justify-center gap-4">
              <button onClick={exportCSV} className="rounded-xl border border-white/10 bg-white/5 px-6 py-3 text-sm font-medium text-white hover:bg-white/10 transition flex items-center gap-2">
                <Download className="h-4 w-4" /> Export CSV
              </button>
              <button onClick={exportPDF} className="btn-primary text-sm px-6 py-3 flex items-center gap-2">
                <FileText className="h-4 w-4" /> Export Report (TXT)
              </button>
            </div>
            <p className="text-[10px] text-slate-600 mt-4">
              Reports are for informational purposes only. ScamTrace does not guarantee that reports will result in fund recovery.
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
