import { useState, useRef, useEffect } from 'react';
import {
  FileText, Download, CheckCircle2, Clock, Hash, GitBranch,
  User, Shield, AlertTriangle, Landmark, ArrowRight, Printer, Lock, Loader2
} from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';

interface CaseSummary {
  id: string;
  title: string;
  scam_type: string;
  total_loss: number;
  created_at: string;
  status: string;
}

interface EvidenceItem {
  type: string;
  value: string;
  label: string;
}

export function EvidenceBuilder() {
  const { user } = useAuth();
  const [statement, setStatement] = useState('');
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [progress, setProgress] = useState(0);
  const packetIdRef = useRef('');
  const packetHashRef = useRef('');
  const packetTimeRef = useRef('');
  const [cases, setCases] = useState<CaseSummary[]>([]);
  const [selectedCaseId, setSelectedCaseId] = useState('');
  const [caseEvidence, setCaseEvidence] = useState<EvidenceItem[]>([]);
  const [loadingCases, setLoadingCases] = useState(false);

  // Fetch user's cases
  useEffect(() => {
    if (!user) return;
    setLoadingCases(true);
    supabase.from('cases').select('id, title, scam_type, total_loss, created_at, status')
      .order('created_at', { ascending: false })
      .then(({ data }) => {
        setCases(data || []);
        setLoadingCases(false);
      });
  }, [user]);

  // Fetch evidence when case is selected
  useEffect(() => {
    if (!selectedCaseId) { setCaseEvidence([]); return; }
    supabase.from('evidence').select('type, value, label')
      .eq('case_id', selectedCaseId)
      .then(({ data }) => setCaseEvidence(data || []));
  }, [selectedCaseId]);

  const selectedCase = cases.find(c => c.id === selectedCaseId);

  const handleGenerate = () => {
    if (generating) return;
    setGenerating(true);
    setGenerated(false);
    setProgress(0);
    
    // Generate stable values before animation starts
    packetIdRef.current = 'ST-2024-' + Math.random().toString(36).substring(2, 8).toUpperCase();
    packetHashRef.current = 'sha256-' + Math.random().toString(16).substring(2, 18) + '...' + Math.random().toString(16).substring(2, 10);
    packetTimeRef.current = new Date().toISOString();

    const interval = setInterval(() => {
      setProgress(p => {
        if (p >= 100) {
          clearInterval(interval);
          setGenerating(false);
          setGenerated(true);
          return 100;
        }
        return p + 4;
      });
    }, 80);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const wallets = caseEvidence.filter(e => e.type === 'wallet').map(e => e.value);
    const domains = caseEvidence.filter(e => e.type === 'domain' || e.type === 'url').map(e => e.value);
    const phones = caseEvidence.filter(e => e.type === 'phone').map(e => e.value);
    const emails = caseEvidence.filter(e => e.type === 'email').map(e => e.value);

    const report = `
SCAMTRACE EVIDENCE PACKET
========================
Packet ID: ${packetIdRef.current}
Generated: ${packetTimeRef.current}
Integrity Hash: ${packetHashRef.current}

CASE INFORMATION
----------------
${selectedCase ? `Case: ${selectedCase.title}
Type: ${selectedCase.scam_type}
Status: ${selectedCase.status}
Total Loss: $${selectedCase.total_loss?.toLocaleString() || 0}
Created: ${new Date(selectedCase.created_at).toLocaleDateString()}` : 'No case selected'}

VICTIM STATEMENT
----------------
${statement || 'No statement provided'}

EVIDENCE SUMMARY
----------------
Wallet Addresses (${wallets.length}):
${wallets.length > 0 ? wallets.map((w, i) => `  ${i + 1}. ${w}`).join('\n') : '  None submitted'}

Domains/URLs (${domains.length}):
${domains.length > 0 ? domains.map((d, i) => `  ${i + 1}. ${d}`).join('\n') : '  None submitted'}

Phone Numbers (${phones.length}):
${phones.length > 0 ? phones.map((p, i) => `  ${i + 1}. ${p}`).join('\n') : '  None submitted'}

Emails (${emails.length}):
${emails.length > 0 ? emails.map((e, i) => `  ${i + 1}. ${e}`).join('\n') : '  None submitted'}

Total Evidence Items: ${caseEvidence.length}
Investigation Date: ${new Date().toISOString().split('T')[0]}

This document was generated by ScamTrace and is integrity-verified.
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${packetIdRef.current || 'evidence-packet'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const walletCount = caseEvidence.filter(e => e.type === 'wallet').length;
  const domainCount = caseEvidence.filter(e => e.type === 'domain' || e.type === 'url').length;
  const phoneCount = caseEvidence.filter(e => e.type === 'phone').length;

  const packetSections = [
    { icon: User, label: 'Victim Statement', detail: statement ? 'User-provided statement attached' : 'No statement provided — add one for stronger evidence' },
    { icon: GitBranch, label: 'Wallet Evidence', detail: walletCount > 0 ? `${walletCount} wallet address(es) from case evidence` : 'No wallet evidence — add wallets to your case' },
    { icon: Hash, label: 'Domain/URL Evidence', detail: domainCount > 0 ? `${domainCount} domain(s)/URL(s) from case evidence` : 'No domain evidence' },
    { icon: Clock, label: 'Case Timeline', detail: selectedCase ? `Created ${new Date(selectedCase.created_at).toLocaleDateString()}` : 'Select a case first' },
    { icon: AlertTriangle, label: 'Case Details', detail: selectedCase ? `${selectedCase.scam_type} — $${selectedCase.total_loss?.toLocaleString() || 0} loss` : 'No case selected' },
    { icon: Landmark, label: 'Contact Evidence', detail: phoneCount > 0 ? `${phoneCount} phone number(s) included` : 'No phone evidence' },
    { icon: Shield, label: 'Evidence Summary', detail: `${caseEvidence.length} total evidence items from Supabase` },
    { icon: Lock, label: 'Evidence Integrity', detail: 'SHA-256 hash of complete evidence packet' },
  ];

  return (
    <section id="evidence" className="relative py-24 grid-bg">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute left-1/4 bottom-0 h-[500px] w-[500px] rounded-full bg-cyber-purple/[0.03] blur-[150px]" />
      </div>

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-cyber-orange/20 bg-cyber-orange/5 px-4 py-1.5">
            <span className="text-xs font-medium text-cyber-orange">Automated Evidence Generation</span>
          </div>
          <h2 className="text-3xl font-extrabold text-white sm:text-4xl lg:text-5xl">
            Freeze-Ready <span className="gradient-text">Evidence Packets</span>
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-slate-400">
            Auto-generate comprehensive evidence packets with timestamped wallet graphs, transaction hashes, and user statements — ready for exchange freeze requests and law enforcement.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Left: Input form */}
          <div className="space-y-6">
            <div className="glass-card rounded-xl p-6">
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold text-white">
                <User className="h-5 w-5 text-cyber-green" />
                Victim Statement
              </h3>
              <textarea
                className="w-full rounded-lg border border-white/10 bg-dark-900 p-4 text-sm text-white placeholder-slate-500 outline-none transition focus:border-cyber-green/50 resize-none"
                rows={6}
                placeholder="Describe how the scam occurred, when you sent funds, what the scammer promised, and any communication records you have..."
                value={statement}
                onChange={e => setStatement(e.target.value)}
              />
              <p className="mt-2 text-xs text-slate-500">
                Your statement will be included in the evidence packet. Be as detailed as possible for stronger cases.
              </p>
            </div>

            <div className="glass-card rounded-xl p-6">
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold text-white">
                <FileText className="h-5 w-5 text-cyber-blue" />
                Select Case
              </h3>

              {!user && (
                <p className="text-sm text-slate-500 py-4 text-center">Sign in to load your cases and generate evidence packets.</p>
              )}

              {user && loadingCases && (
                <div className="flex items-center justify-center py-4">
                  <Loader2 className="h-5 w-5 animate-spin text-cyber-blue" />
                </div>
              )}

              {user && !loadingCases && cases.length === 0 && (
                <p className="text-sm text-slate-500 py-4 text-center">No cases found. Submit a scam report first.</p>
              )}

              {user && !loadingCases && cases.length > 0 && (
                <div className="space-y-3">
                  <select
                    value={selectedCaseId}
                    onChange={e => setSelectedCaseId(e.target.value)}
                    className="w-full appearance-none rounded-xl border border-white/10 bg-dark-900 px-4 py-3 text-sm text-white outline-none focus:border-cyber-green/50 transition cursor-pointer"
                  >
                    <option value="">Select a case...</option>
                    {cases.map(c => (
                      <option key={c.id} value={c.id}>{c.title || c.scam_type} - ${c.total_loss?.toLocaleString() || 0}</option>
                    ))}
                  </select>

                  {selectedCase && (
                    <div className="space-y-2">
                      {[
                        { label: 'Case', value: selectedCase.title || selectedCase.scam_type, color: 'text-white' },
                        { label: 'Type', value: selectedCase.scam_type, color: 'text-cyber-blue' },
                        { label: 'Total Loss', value: `$${selectedCase.total_loss?.toLocaleString() || 0}`, color: 'text-cyber-red' },
                        { label: 'Status', value: selectedCase.status, color: 'text-cyber-green' },
                        { label: 'Evidence Items', value: String(caseEvidence.length), color: 'text-amber-400' },
                        { label: 'Wallets', value: String(caseEvidence.filter(e => e.type === 'wallet').length), color: 'text-cyber-orange' },
                        { label: 'Date', value: new Date(selectedCase.created_at).toLocaleDateString(), color: 'text-slate-300' },
                      ].map(item => (
                        <div key={item.label} className="flex items-center justify-between border-b border-white/5 pb-2">
                          <span className="text-xs text-slate-400">{item.label}</span>
                          <span className={`text-sm font-medium ${item.color} font-mono`}>{item.value}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyber-green to-cyber-blue py-4 text-base font-bold text-dark-900 shadow-lg shadow-cyber-green/20 transition-all hover:shadow-cyber-green/40 disabled:opacity-50"
            >
              {generating ? (
                <>Generating Evidence Packet... {progress}%</>
              ) : generated ? (
                <><CheckCircle2 className="h-5 w-5" /> Regenerate Evidence Packet</>
              ) : (
                <><FileText className="h-5 w-5" /> Generate Evidence Packet</>
              )}
            </button>

            {generating && (
              <div className="h-1.5 overflow-hidden rounded-full bg-dark-700">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-cyber-green to-cyber-blue transition-all duration-100"
                  style={{ width: `${progress}%` }}
                />
              </div>
            )}
          </div>

          {/* Right: Generated packet preview */}
          <div className="glass-card rounded-xl p-6">
            <div className="mb-6 flex items-center justify-between flex-wrap gap-2">
              <h3 className="flex items-center gap-2 text-lg font-bold text-white">
                <Shield className="h-5 w-5 text-cyber-orange" />
                Evidence Packet
              </h3>
              {generated && (
                <div className="flex items-center gap-2">
                  <button 
                    onClick={handlePrint}
                    className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-white/10"
                  >
                    <Printer className="h-3.5 w-3.5" /> Print
                  </button>
                  <button 
                    onClick={handleDownload}
                    className="flex items-center gap-1.5 rounded-lg bg-cyber-green/10 px-3 py-1.5 text-xs font-medium text-cyber-green transition hover:bg-cyber-green/20"
                  >
                    <Download className="h-3.5 w-3.5" /> Download
                  </button>
                </div>
              )}
            </div>

            <div className="space-y-3">
              {packetSections.map((section, idx) => {
                const isProcessed = generating && progress > (idx + 1) * 12;
                return (
                  <div
                    key={section.label}
                    className={`flex items-center gap-3 rounded-lg border p-3 transition-all duration-500 ${
                      generated
                        ? 'border-cyber-green/20 bg-cyber-green/5'
                        : isProcessed
                        ? 'border-cyber-blue/20 bg-cyber-blue/5'
                        : 'border-white/5 bg-white/[0.02]'
                    }`}
                  >
                    <div className={`flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg ${
                      generated ? 'bg-cyber-green/10' : isProcessed ? 'bg-cyber-blue/10' : 'bg-white/5'
                    }`}>
                      {generated ? (
                        <CheckCircle2 className="h-4 w-4 text-cyber-green" />
                      ) : isProcessed ? (
                        <CheckCircle2 className="h-4 w-4 text-cyber-blue" />
                      ) : (
                        <section.icon className="h-4 w-4 text-slate-400" />
                      )}
                    </div>
                    <div className="flex-grow min-w-0">
                      <div className="text-sm font-medium text-white">{section.label}</div>
                      <div className="text-xs text-slate-400 truncate">{section.detail}</div>
                    </div>
                    {generated && (
                      <span className="text-[10px] font-medium text-cyber-green uppercase flex-shrink-0">included</span>
                    )}
                  </div>
                );
              })}
            </div>

            {generated && (
              <div className="mt-6 space-y-3 animate-fade-in-up">
                <div className="rounded-lg border border-cyber-green/20 bg-cyber-green/5 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium text-cyber-green">
                    <CheckCircle2 className="h-4 w-4" />
                    Evidence Packet Generated Successfully
                  </div>
                  <p className="mt-1 text-xs text-slate-400">
                    Your evidence packet contains all necessary documentation for an exchange freeze request.
                    The packet is integrity-verified with SHA-256 hashing.
                  </p>
                </div>

                {selectedCase && (
                  <div className="rounded-lg border border-cyber-orange/20 bg-cyber-orange/5 p-4">
                    <div className="flex items-center gap-2 text-sm font-medium text-cyber-orange">
                      <Landmark className="h-4 w-4" />
                      Evidence Packet for: {selectedCase.title || selectedCase.scam_type}
                    </div>
                    <p className="mt-1 text-xs text-slate-400">
                      {caseEvidence.length} evidence items included. Loss: ${selectedCase.total_loss?.toLocaleString() || 0}.
                      Download the packet and submit to relevant exchanges or law enforcement.
                    </p>
                    <button onClick={handleDownload} className="mt-2 flex items-center gap-1 text-xs font-medium text-cyber-orange hover:underline transition">
                      Download Full Report <ArrowRight className="h-3 w-3" />
                    </button>
                  </div>
                )}

                <div className="rounded-lg bg-dark-900 p-3 font-mono text-xs text-slate-500 space-y-1">
                  <div>Packet ID: {packetIdRef.current}</div>
                  <div>Generated: {packetTimeRef.current}</div>
                  <div className="break-all">Hash: {packetHashRef.current}</div>
                </div>
              </div>
            )}

            {!generated && !generating && (
              <div className="mt-6 flex flex-col items-center justify-center py-8 text-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/5 mb-3">
                  <FileText className="h-7 w-7 text-slate-600" />
                </div>
                <p className="text-sm text-slate-500">
                  Click &quot;Generate Evidence Packet&quot; to create your freeze-ready documentation
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
