import { useState, useRef } from 'react';
import {
  FileText, Download, CheckCircle2, Clock, Hash, GitBranch,
  User, Shield, AlertTriangle, Landmark, ArrowRight, Printer, Lock
} from 'lucide-react';

export function EvidenceBuilder() {
  const [statement, setStatement] = useState('');
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [progress, setProgress] = useState(0);
  const packetIdRef = useRef('');
  const packetHashRef = useRef('');
  const packetTimeRef = useRef('');

  const handleGenerate = () => {
    if (generating) return;
    setGenerating(true);
    setGenerated(false);
    setProgress(0);
    
    // Generate stable values before animation starts
    packetIdRef.current = 'ST-2024-' + Math.random().toString(36).substring(2, 8).toUpperCase();
    packetHashRef.current = 'sha256-' + Math.random().toString(16).substring(2, 18) + '...' + Math.random().toString(16).substring(2, 10);
    packetTimeRef.current = new Date().toISOString();

    const interval = setInterval(() => {
      setProgress(p => {
        if (p >= 100) {
          clearInterval(interval);
          setGenerating(false);
          setGenerated(true);
          return 100;
        }
        return p + 4;
      });
    }, 80);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    // Generate a text-based evidence report
    const report = `
SCAMTRACE EVIDENCE PACKET
========================
Packet ID: ${packetIdRef.current}
Generated: ${packetTimeRef.current}
Integrity Hash: ${packetHashRef.current}

VICTIM STATEMENT
----------------
${statement || 'No statement provided'}

INVESTIGATION SUMMARY
--------------------
Source Address: 0x7a250d...dEad
Total Amount: 12.5 ETH + 0.27 BTC (~$45,500 USD)
Chains Involved: Ethereum, Bitcoin, Polygon, Arbitrum
Mixers Detected: 2 (Tornado Cash + Wasabi CoinJoin)
Bridges Used: 3 (Hop Protocol, RenBridge to BTC)
Exchange Deposits: 2 (Binance + Kraken)
Investigation Date: ${new Date().toISOString().split('T')[0]}

RISK ASSESSMENT
--------------
Risk Score: 97/100 - CRITICAL
Flags: ETH Mixer, BTC CoinJoin, Cross-chain bridges, Multi-exchange deposits, BTC UTXO laundering

TRANSACTION HASHES
-----------------
1. 0xabc123...def456 - Split (Ethereum)
2. 0x789abc...123def - Split (Ethereum)
3. 0xmix001...fed321 - Mixer / Tornado Cash (Ethereum)
4. 0xbrg001...abc789 - Bridge (ETH→Polygon)
5. 0xpost01...mix456 - Transfer (Ethereum)
6. 0xpoly01...brg789 - Transfer (Polygon)
7. 0xexch01...dep123 - Exchange Deposit / Binance (Ethereum)
8. 0xarb001...brg456 - Bridge (Poly→Arb)
9. 0xswap01...dex789 - DEX Swap (Arbitrum)
10. 0xren01...btc789 - Bridge / RenBridge (Arb→Bitcoin)
11. btc:a1b2c3...d4e5f6 - Mixer / Wasabi CoinJoin (Bitcoin)
12. btc:f6e5d4...c3b2a1 - Exchange Deposit / Kraken (Bitcoin)

EXCHANGE FREEZE REQUEST #1
--------------------------
Target Exchange: Binance
Wallet: 0xbin...hot1
Amount: 4.8 ETH
Chain: Ethereum
Request: Immediate freeze pending investigation

EXCHANGE FREEZE REQUEST #2
--------------------------
Target Exchange: Kraken
Wallet: bc1q...ex3p
Amount: 0.25 BTC
Chain: Bitcoin
Request: Immediate freeze pending investigation — BTC deposited after CoinJoin mixing

BITCOIN NETWORK ANALYSIS
------------------------
Entry Point: RenBridge cross-chain swap from Arbitrum
BTC Received: 0.27 BTC at renBTC...v8k2
Mixer Used: Wasabi Wallet CoinJoin (bc1q...m4x7)
Post-Mix Output: 0.26 BTC (mixing fee: ~0.01 BTC)
Final Destination: Kraken exchange deposit (bc1q...ex3p, 0.25 BTC)
UTXO Analysis: Change address analysis confirmed output ownership

This document was generated by ScamTrace and is integrity-verified.
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${packetIdRef.current || 'evidence-packet'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const packetSections = [
    { icon: User, label: 'Victim Statement', detail: statement ? 'User-provided statement attached' : 'No statement provided — add one for stronger evidence' },
    { icon: GitBranch, label: 'Wallet Graph', detail: '13 nodes, 12 edges, 5 chains (incl. Bitcoin)' },
    { icon: Hash, label: 'Transaction Hashes', detail: '12 transaction hashes with timestamps (ETH + BTC)' },
    { icon: Clock, label: 'Timeline', detail: 'Complete chronological event log' },
    { icon: AlertTriangle, label: 'Risk Assessment', detail: 'AI-generated risk score: 97/100 CRITICAL (ETH + BTC)' },
    { icon: Landmark, label: 'Exchange Contact Info', detail: 'Binance + Kraken compliance team contacts' },
    { icon: Shield, label: 'Freeze Request Templates', detail: 'Pre-filled freeze requests for Binance (ETH) + Kraken (BTC)' },
    { icon: Lock, label: 'Evidence Integrity', detail: 'SHA-256 hash of complete evidence packet' },
  ];

  return (
    <section id="evidence" className="relative py-24 grid-bg">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute left-1/4 bottom-0 h-[500px] w-[500px] rounded-full bg-cyber-purple/[0.03] blur-[150px]" />
      </div>

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-cyber-orange/20 bg-cyber-orange/5 px-4 py-1.5">
            <span className="text-xs font-medium text-cyber-orange">Automated Evidence Generation</span>
          </div>
          <h2 className="text-3xl font-extrabold text-white sm:text-4xl lg:text-5xl">
            Freeze-Ready <span className="gradient-text">Evidence Packets</span>
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-slate-400">
            Auto-generate comprehensive evidence packets with timestamped wallet graphs, transaction hashes, and user statements — ready for exchange freeze requests and law enforcement.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Left: Input form */}
          <div className="space-y-6">
            <div className="glass-card rounded-xl p-6">
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold text-white">
                <User className="h-5 w-5 text-cyber-green" />
                Victim Statement
              </h3>
              <textarea
                className="w-full rounded-lg border border-white/10 bg-dark-900 p-4 text-sm text-white placeholder-slate-500 outline-none transition focus:border-cyber-green/50 resize-none"
                rows={6}
                placeholder="Describe how the scam occurred, when you sent funds, what the scammer promised, and any communication records you have..."
                value={statement}
                onChange={e => setStatement(e.target.value)}
              />
              <p className="mt-2 text-xs text-slate-500">
                Your statement will be included in the evidence packet. Be as detailed as possible for stronger cases.
              </p>
            </div>

            <div className="glass-card rounded-xl p-6">
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold text-white">
                <FileText className="h-5 w-5 text-cyber-blue" />
                Investigation Summary
              </h3>
              <div className="space-y-3">
                {[
                  { label: 'Source Address', value: '0x7a250d...dEad', color: 'text-cyber-red' },
                  { label: 'Total Amount', value: '12.5 ETH + 0.27 BTC (~$45,500)', color: 'text-white' },
                  { label: 'Chains Involved', value: 'Ethereum, Bitcoin, Polygon, Arbitrum', color: 'text-cyber-blue' },
                  { label: 'Mixers Detected', value: '2 (Tornado Cash + Wasabi CoinJoin)', color: 'text-cyber-orange' },
                  { label: 'Bridges Used', value: '3 (Hop Protocol, RenBridge)', color: 'text-cyber-orange' },
                  { label: 'Exchange Deposits', value: '2 (Binance + Kraken)', color: 'text-cyber-green' },
                  { label: 'Investigation Date', value: new Date().toISOString().split('T')[0], color: 'text-slate-300' },
                ].map(item => (
                  <div key={item.label} className="flex items-center justify-between border-b border-white/5 pb-2">
                    <span className="text-xs text-slate-400">{item.label}</span>
                    <span className={`text-sm font-medium ${item.color} font-mono`}>{item.value}</span>
                  </div>
                ))}
              </div>
            </div>

            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyber-green to-cyber-blue py-4 text-base font-bold text-dark-900 shadow-lg shadow-cyber-green/20 transition-all hover:shadow-cyber-green/40 disabled:opacity-50"
            >
              {generating ? (
                <>Generating Evidence Packet... {progress}%</>
              ) : generated ? (
                <><CheckCircle2 className="h-5 w-5" /> Regenerate Evidence Packet</>
              ) : (
                <><FileText className="h-5 w-5" /> Generate Evidence Packet</>
              )}
            </button>

            {generating && (
              <div className="h-1.5 overflow-hidden rounded-full bg-dark-700">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-cyber-green to-cyber-blue transition-all duration-100"
                  style={{ width: `${progress}%` }}
                />
              </div>
            )}
          </div>

          {/* Right: Generated packet preview */}
          <div className="glass-card rounded-xl p-6">
            <div className="mb-6 flex items-center justify-between flex-wrap gap-2">
              <h3 className="flex items-center gap-2 text-lg font-bold text-white">
                <Shield className="h-5 w-5 text-cyber-orange" />
                Evidence Packet
              </h3>
              {generated && (
                <div className="flex items-center gap-2">
                  <button 
                    onClick={handlePrint}
                    className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-white/10"
                  >
                    <Printer className="h-3.5 w-3.5" /> Print
                  </button>
                  <button 
                    onClick={handleDownload}
                    className="flex items-center gap-1.5 rounded-lg bg-cyber-green/10 px-3 py-1.5 text-xs font-medium text-cyber-green transition hover:bg-cyber-green/20"
                  >
                    <Download className="h-3.5 w-3.5" /> Download
                  </button>
                </div>
              )}
            </div>

            <div className="space-y-3">
              {packetSections.map((section, idx) => {
                const isProcessed = generating && progress > (idx + 1) * 12;
                return (
                  <div
                    key={section.label}
                    className={`flex items-center gap-3 rounded-lg border p-3 transition-all duration-500 ${
                      generated
                        ? 'border-cyber-green/20 bg-cyber-green/5'
                        : isProcessed
                        ? 'border-cyber-blue/20 bg-cyber-blue/5'
                        : 'border-white/5 bg-white/[0.02]'
                    }`}
                  >
                    <div className={`flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg ${
                      generated ? 'bg-cyber-green/10' : isProcessed ? 'bg-cyber-blue/10' : 'bg-white/5'
                    }`}>
                      {generated ? (
                        <CheckCircle2 className="h-4 w-4 text-cyber-green" />
                      ) : isProcessed ? (
                        <CheckCircle2 className="h-4 w-4 text-cyber-blue" />
                      ) : (
                        <section.icon className="h-4 w-4 text-slate-400" />
                      )}
                    </div>
                    <div className="flex-grow min-w-0">
                      <div className="text-sm font-medium text-white">{section.label}</div>
                      <div className="text-xs text-slate-400 truncate">{section.detail}</div>
                    </div>
                    {generated && (
                      <span className="text-[10px] font-medium text-cyber-green uppercase flex-shrink-0">included</span>
                    )}
                  </div>
                );
              })}
            </div>

            {generated && (
              <div className="mt-6 space-y-3 animate-fade-in-up">
                <div className="rounded-lg border border-cyber-green/20 bg-cyber-green/5 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium text-cyber-green">
                    <CheckCircle2 className="h-4 w-4" />
                    Evidence Packet Generated Successfully
                  </div>
                  <p className="mt-1 text-xs text-slate-400">
                    Your evidence packet contains all necessary documentation for an exchange freeze request.
                    The packet is integrity-verified with SHA-256 hashing.
                  </p>
                </div>

                <div className="rounded-lg border border-cyber-orange/20 bg-cyber-orange/5 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium text-cyber-orange">
                    <Landmark className="h-4 w-4" />
                    Binance Freeze Request Ready (4.8 ETH)
                  </div>
                  <p className="mt-1 text-xs text-slate-400">
                    ETH deposit detected at Binance hot wallet. A pre-filled freeze request has been included.
                  </p>
                  <button className="mt-2 flex items-center gap-1 text-xs font-medium text-cyber-orange hover:underline transition">
                    Send Freeze Request <ArrowRight className="h-3 w-3" />
                  </button>
                </div>

                <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium text-amber-400">
                    <span className="text-base">₿</span>
                    Kraken Freeze Request Ready (0.25 BTC)
                  </div>
                  <p className="mt-1 text-xs text-slate-400">
                    BTC deposit detected at Kraken after Wasabi CoinJoin mixing. Freeze request includes UTXO analysis and CoinJoin output tracing.
                  </p>
                  <button className="mt-2 flex items-center gap-1 text-xs font-medium text-amber-400 hover:underline transition">
                    Send BTC Freeze Request <ArrowRight className="h-3 w-3" />
                  </button>
                </div>

                <div className="rounded-lg bg-dark-900 p-3 font-mono text-xs text-slate-500 space-y-1">
                  <div>Packet ID: {packetIdRef.current}</div>
                  <div>Generated: {packetTimeRef.current}</div>
                  <div className="break-all">Hash: {packetHashRef.current}</div>
                </div>
              </div>
            )}

            {!generated && !generating && (
              <div className="mt-6 flex flex-col items-center justify-center py-8 text-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/5 mb-3">
                  <FileText className="h-7 w-7 text-slate-600" />
                </div>
                <p className="text-sm text-slate-500">
                  Click &quot;Generate Evidence Packet&quot; to create your freeze-ready documentation
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
